/*
 * This source file was generated by the Gradle 'init' task
 */
package collections1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static void basicArraysExample() {
        // Create an array of integers
        int[] numbers = {1, 2, 3, 4, 5};
        for (int num : numbers) {
            System.out.println(num);
        }

        String[] names = new String[3];
        names[0] = "Alice";
        names[1] = "Bob";
        names[2] = "Charlie";
        for (String name : names) {
            System.out.println(name);
        }
        
        class MyCatInto {
            String name;
            int age;
            String catType;

            MyCatInto(String name, int age, String catType) {
                this.name = name;
                this.age = age;
                this.catType = catType;
            }

            @Override
            public String toString() {
                return "name='" + name + "', age=" + age + ", catType='" + catType + "'";
            }
        }
        MyCatInto[] cats = {
            new MyCatInto("Whiskers", 2, "Siamese"),
            new MyCatInto("Mittens", 3, "Persian"),
            new MyCatInto("Shadow", 1, "Maine")
        };
        for (MyCatInto cat : cats) {
            System.out.println(cat);    
        }
    }   
}
